'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { api,getToken } from '../../../lib/api';
import type {User} from '../../../types';
export default function NewTask(){const router=useRouter();const [users,setUsers]=useState<User[]>([]);const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [assigned,setAssigned]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!getToken()){router.replace('/login');return}api('/users').then(d=>setUsers(d.users)).catch(e=>setError(e.message))},[router]);
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{await api('/tasks',{method:'POST',body:JSON.stringify({title,description,assigned_to:assigned})});router.push('/dashboard')}catch(e){setError(e instanceof Error?e.message:'Could not create task')}finally{setSaving(false)}}
 return <main className="container" style={{maxWidth:700}}><div className="topbar"><div><div className="brand">TaskFlow</div><span className="muted">Create a task</span></div><button className="btn secondary" onClick={()=>router.back()}>Back</button></div><div className="card"><form className="form" onSubmit={submit}><div><div className="label">Title</div><input className="input" value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} required placeholder="e.g. Prepare project report"/></div><div><div className="label">Description</div><textarea className="textarea" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Add useful context..."/></div><div><div className="label">Assign to</div><select className="input" value={assigned} onChange={e=>setAssigned(e.target.value)} required><option value="">Select a user</option>{users.map(u=><option key={u.id} value={u.id}>{u.name} — {u.email}</option>)}</select></div>{error&&<div className="error">{error}</div>}<button className="btn" disabled={saving}>{saving?'Creating...':'Create task'}</button></form></div></main>}
